dist: trusty
sudo: false
group: beta
language: node_js
node_js:
- 10.3.0
jobs:
  include:
  - stage: test
    script:
    - set -e
    - npm run flow
    - npm run lint
    - npm run test
    - npm run coverage
  - stage: NPM release
    if: tag IS present
    script: echo 'Deploying to NPM...'
    before_deploy: npm run build
    deploy:
      provider: npm
      email: chadima.jiri@gmail.com
      skip_cleanup: true
      api_key: "$NPM_TOKEN"
      on:
        repo: windingtree/off-chain-adapter-swarm
        tags: true
env:
  global:
    secure: Xmvh9D9ZhYLNiQaCdI/8GR/t2PKJ0XsnwJWad7zhvPT7tc8pDey20gf3dnbCtji+Xd0HPRlNyI+AN/DGKeQiLhJ5rI+gxk58vMG6g6BOafu9ZYOjIB8a/MQHDRL1vsm678/nh6l0XTkZ8UCRO8ruOVVsndQnZdVDohEXwFARzcDZQmTNYZRiPqDlFgJeKc/rSZgdDKRXgTyuMPs5ctYO305LxFL3BQEgBlqhvU0Y8kaUuXlAj5CS+ocqCcn17uxNn42oNf+UZkA8adckSPzCvCmigTQGS9Nr5ebtB/yg7g8cKnIAF9lA55HHL/miPJI2d27PRRMomk547RnidKidxNDmbwRyaXE/43riT+rkICFvJhCjz6eoGG0OQwP/RczYjTd8F08MFrERtz8XgvkhPLEhlpurLqTKmS/dKRRsZ7k96Bu+qsFtp7ZFW4sp7lA0r98splqZQJStgUZOziPH0LKM5ULI0zSg0j2GfXq/PBMgTbKQN8VJMKLFDfdwMcXYh3D7RewPAKRClIDHXWkvKojQ1VQkcbCOqS4sZ69UZQ52SzG2L46Lgr720nRmpFSxOGyVbys/cMO3uvEmjE8u6bjnpXPXeHT58xjkJ60Qy79BHb0ogJVEvJJee49gNBVer76/T+D6MSONwAoykosR8OjzgYz4e6WKiPGKbcxMMms=
