dist: trusty
sudo: false
group: beta
language: node_js
node_js:
- '8'
jobs:
  include:
  - stage: test
    script:
    - set -e
    - npm run flow
    - npm run lint
    - npm run test
    - npm run coverage
