dist: trusty
sudo: false
group: beta
language: node_js
node_js:
- 10.3.0
jobs:
  include:
  - stage: test
    script:
    - set -e
    - npm run flow
    - npm run lint
    - npm run test
    - npm run coverage
  - stage: NPM release
    if: tag IS present
    script: echo 'Deploying to NPM...'
    before_deploy: npm run build
    deploy:
      provider: npm
      email: chadima.jiri@gmail.com
      skip_cleanup: true
      api_key: "$NPM_TOKEN"
      on:
        repo: windingtree/off-chain-adapter-swarm
        tags: true
env:
  global:
    secure: CF42J+m8khSWemUBYmbt5pg9LxsHfaHGV7yB018bpAac2tvPBfQ+cCwKbWCaGb7GATP1D0GmvENcu/ICsXQcajlBlwux3Ro24r3oRjFaXX0StqHQv280MwyxZvMTvw0vVYAabnBtP9E4rA+1Gv/usuymv7+EbFXiRMlcf51jvgHRJldOBAnPQx55qAFUAPqhBw/ByfxqQYVQFGZ+O4Ur8I1yU5PCWl1r2oX4Uq6444CElwBXKXPRL8yZLy9UygapUKgyMu5BcXS8y5dztlV+Gaxh/wvR+HpAiSCYwQ7LyBzzvG83kc4AppkmBfxZRTY0mrq1cf4jfcR2LinPGDHM0po4if8nGBis54V3SWpzdlM5p6LD3QPUyAmLL12AiRweH+dqJ3tj2E8tKb3jOG8rJOLTm2ty4AI4Rr38kSBp0EmkwmcSzLLnFUpb7+s+gQ0G4kRp5BI/ZGX8apSxPZqk9UWebqbYoChHbGxIrxnGFiHMzjXYFB6nSom6OJZVOwPypIFxAdEMWwWcIE2V5nNUo2iFfkdteXHFHVSyF1EtxOPL8wcXodNvEmE7NJZFSW11UN71BBNQKhS4O3N8sJM9i7IS0ZHN4HbnZrSrAv/h/xn8/ohHHPgZ+ogNnFLQCEG6jKZjMM5ylFuJsiJYDEYnBLWyuI87xZxAgipWk69mSZE=
